
repos:
  - repo: local
    hooks:
      - id: venv-generate-requirements
        name: Update requirements.txt from venv
        entry: bash -c '. venv/bin/activate && pip freeze > requirements.txt && git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [commit]
        types: [python]
