repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: venv/bin/black src/
        language: system
        stages: [pre-commit]
        exclude: ^(?!src/).*  # Exclui arquivos fora da pasta 'src'

      - id: flake8
        name: flake8
        entry: venv/bin/flake8 src/
        language: system
        stages: [pre-commit]
        exclude: ^(?!src/).*  # Exclui arquivos fora da pasta 'src'

      - id: pylint
        name: pylint
        entry: venv/bin/pylint src/
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: pytest
        name: pytest
        language: system
        entry: venv/bin/pytest -v
        always_run: true
        pass_filenames: false
        stages: [pre-commit]

      - id: requirements
        name: requirements
        entry: bash -c 'venv/bin/pip3 freeze > requirements.txt && git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [pre-commit]
