

services:

  mysqldb:
    image: mysql:8.4
    environment:
      - MYSQL_ROOT_PASSWORD=senha
      - MYSQL_DATABASE=public
    volumes:
      - mysqlVolume:/var/lib/mysql
      - mysqlConfig:/etc/mysql
    restart: always 
    ports:
      - "3305:3306"

volumes:
  mysqlVolume:
  mysqlConfig:



